"""Post-run analysis of fuzzing results into categorized findings."""

from .findings import (
    Finding,
    analyze_findings,
    summarize_findings,
)
from .auth_probe import (
    is_auth_enforced,
    probe_advertised_auth_open_tools,
    probe_auth_bypass,
    secured_tool_names,
)
from .auth_audit import (
    AUTH_AUDIT_FLAW_CATEGORIES,
    AUTH_AUDIT_PAPER_URL,
    audit_as_metadata,
    auth_audit_paper_evidence,
    auth_audit_report_metadata,
    discover_and_audit_authorization_server,
    inspect_state_for_routing,
    is_auth_audit_finding,
    probe_blind_client_trust,
    probe_code_replay,
    probe_consent_page_bypass,
    probe_malicious_dcr,
    probe_open_redirect,
    probe_pkce_downgrade_active,
    probe_pkce_layer_inconsistency,
    probe_weak_state,
    run_auth_endpoint_audit,
    run_post_authorization_audit,
)

__all__ = [
    "Finding",
    "analyze_findings",
    "summarize_findings",
    "is_auth_enforced",
    "probe_advertised_auth_open_tools",
    "probe_auth_bypass",
    "secured_tool_names",
    "AUTH_AUDIT_FLAW_CATEGORIES",
    "AUTH_AUDIT_PAPER_URL",
    "audit_as_metadata",
    "auth_audit_paper_evidence",
    "auth_audit_report_metadata",
    "discover_and_audit_authorization_server",
    "inspect_state_for_routing",
    "is_auth_audit_finding",
    "probe_blind_client_trust",
    "probe_code_replay",
    "probe_consent_page_bypass",
    "probe_malicious_dcr",
    "probe_open_redirect",
    "probe_pkce_downgrade_active",
    "probe_pkce_layer_inconsistency",
    "probe_weak_state",
    "run_auth_endpoint_audit",
    "run_post_authorization_audit",
]
