"""Central registry for MCP protocol types used across fuzzing components."""

PROTOCOL_TYPES: tuple[str, ...] = (
    "InitializeRequest",
    "InitializedNotification",
    "ProgressNotification",
    "CancelledNotification",
    "ListToolsRequest",
    "CallToolRequest",
    "ListResourcesRequest",
    "ReadResourceRequest",
    "SetLevelRequest",
    "GenericJSONRPCRequest",
    "CallToolResult",
    "SamplingMessage",
    "CreateMessageRequest",
    "ListPromptsRequest",
    "GetPromptRequest",
    "ListRootsRequest",
    "SubscribeRequest",
    "UnsubscribeRequest",
    "CompleteRequest",
    "ListResourceTemplatesRequest",
    "ElicitRequest",
    "PingRequest",
    # Result schemas
    "InitializeResult",
    "ListResourcesResult",
    "ListResourceTemplatesResult",
    "ReadResourceResult",
    "ListPromptsResult",
    "GetPromptResult",
    "ListToolsResult",
    "CompleteResult",
    "CreateMessageResult",
    "ListRootsResult",
    "CreateTaskResult",
    "GetTaskResult",
    "GetTaskPayloadResult",
    "ListTasksResult",
    "CancelTaskResult",
    "EmptyResult",
    "ElicitResult",
    # Notification schemas
    "LoggingMessageNotification",
    "ResourceListChangedNotification",
    "ResourceUpdatedNotification",
    "PromptListChangedNotification",
    "ToolListChangedNotification",
    "RootsListChangedNotification",
    "ElicitationCompleteNotification",
    "TaskStatusNotification",
    # Task request schemas
    "ListTasksRequest",
    "GetTaskRequest",
    "GetTaskPayloadRequest",
    "CancelTaskRequest",
    # Content block schemas
    "TextContent",
    "ImageContent",
    "AudioContent",
    # Resource schemas
    "Resource",
    "ResourceTemplate",
    "TextResourceContents",
    "BlobResourceContents",
    # Tool schemas
    "Tool",
)

DEFAULT_PROTOCOL_TYPES: tuple[str, ...] = (
    "InitializeRequest",
    "InitializedNotification",
    "ListToolsRequest",
    "CallToolRequest",
    "ListResourcesRequest",
    "ReadResourceRequest",
    "ListPromptsRequest",
    "GetPromptRequest",
    "ListRootsRequest",
    "SetLevelRequest",
    "CompleteRequest",
    "ListResourceTemplatesRequest",
    "ElicitRequest",
    "PingRequest",
    "SubscribeRequest",
    "UnsubscribeRequest",
    "CreateMessageRequest",
    "ListTasksRequest",
    "GetTaskRequest",
    "GetTaskPayloadRequest",
    "CancelTaskRequest",
)
