name: Component Tests

on:
  workflow_dispatch:
    inputs:
      components:
        description: "Comma-separated components to run (auth,cli,client,fuzz_engine,safety,transport)"
        required: false
        default: ""

jobs:
  component-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for git diff

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest pytest-cov pytest-asyncio

      - name: Determine changed components
        id: changes
        run: |
          # If manual input is provided, use that. Otherwise, run all components.
          INPUTS="${{ github.event.inputs.components }}"
          if [ -n "$INPUTS" ]; then
            AUTH_CHANGES=$(echo "$INPUTS" | grep -q "auth" && echo "true" || echo "false")
            CLI_CHANGES=$(echo "$INPUTS" | grep -q "cli" && echo "true" || echo "false")
            CLIENT_CHANGES=$(echo "$INPUTS" | grep -q "client" && echo "true" || echo "false")
            FUZZ_ENGINE_CHANGES=$(echo "$INPUTS" | grep -q "fuzz_engine" && echo "true" || echo "false")
            SAFETY_CHANGES=$(echo "$INPUTS" | grep -q "safety" && echo "true" || echo "false")
            TRANSPORT_CHANGES=$(echo "$INPUTS" | grep -q "transport" && echo "true" || echo "false")
          else
            # Default to running all components on manual trigger
            AUTH_CHANGES=true
            CLI_CHANGES=true
            CLIENT_CHANGES=true
            FUZZ_ENGINE_CHANGES=true
            SAFETY_CHANGES=true
            TRANSPORT_CHANGES=true
          fi

          echo "auth=$AUTH_CHANGES" >> $GITHUB_OUTPUT
          echo "cli=$CLI_CHANGES" >> $GITHUB_OUTPUT
          echo "client=$CLIENT_CHANGES" >> $GITHUB_OUTPUT
          echo "fuzz_engine=$FUZZ_ENGINE_CHANGES" >> $GITHUB_OUTPUT
          echo "safety=$SAFETY_CHANGES" >> $GITHUB_OUTPUT
          echo "transport=$TRANSPORT_CHANGES" >> $GITHUB_OUTPUT

      - name: Run auth tests
        if: steps.changes.outputs.auth == 'true'
        run: pytest -vv tests/unit/auth --cov=mcp_fuzzer.auth --cov-report=xml:coverage.auth.xml

      - name: Run CLI tests
        if: steps.changes.outputs.cli == 'true'
        run: pytest -vv tests/unit/cli --cov=mcp_fuzzer.cli --cov-report=xml:coverage.cli.xml

      - name: Run client tests
        if: steps.changes.outputs.client == 'true'
        run: pytest -vv tests/unit/client --cov=mcp_fuzzer.client --cov-report=xml:coverage.client.xml

      - name: Run fuzz engine tests
        if: steps.changes.outputs.fuzz_engine == 'true'
        run: pytest -vv tests/unit/fuzz_engine --cov=mcp_fuzzer.fuzz_engine --cov-report=xml:coverage.fuzz_engine.xml

      - name: Run safety system tests
        if: steps.changes.outputs.safety == 'true'
        run: pytest -vv tests/unit/safety_system --cov=mcp_fuzzer.safety_system --cov-report=xml:coverage.safety_system.xml

      - name: Run transport tests
        if: steps.changes.outputs.transport == 'true'
        run: pytest -vv tests/unit/transport --cov=mcp_fuzzer.transport --cov-report=xml:coverage.transport.xml

      - name: Upload coverage to Codecov
        if: ${{ steps.changes.outputs.auth == 'true' || steps.changes.outputs.cli == 'true' || steps.changes.outputs.client == 'true' || steps.changes.outputs.fuzz_engine == 'true' || steps.changes.outputs.safety == 'true' || steps.changes.outputs.transport == 'true' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.*.xml
          fail_ci_if_error: true
