name: Lint

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install ruff and isort
        run: |
          pip install ruff isort
      - name: Run ruff
        run: |
          ruff .
      - name: Run isort
        run: |
          isort --check --diff . 